# Generated by Django 3.1.7 on 2023-01-28 14:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Annonces', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='annonce',
            name='slug',
            field=models.SlugField(default=django.utils.timezone.now, max_length=250, unique_for_date='published'),
            preserve_default=False,
        ),
    ]
