# Generated by Django 3.1.7 on 2023-01-28 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Annonces', '0003_remove_annonce_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='annonce',
            name='slug',
            field=models.SlugField(default=1, max_length=250),
            preserve_default=False,
        ),
    ]
